### ISSUE TITLE
Identify owning SIG

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/gateway-api-inference-extension#41]
Workgroups are temporary time bounded groups, this project should specify the owning sig and be listed as a subproject of one of the SIGs in the metadata in github.com/kubernetes/community, you can identify the workgroup as a place to discuss the project but it cannot be the owner and we should sort that out sooner than later so we don't have confusion when the workgroup winds down.

cc @kubernetes/steering-committee

**Comment by SergeyKanzhelev** [comment]
sig network or sig autoscaling might be a good home

added as. an agenda item for the wednesday meeting: https://docs.google.com/document/d/1aExJFtaLnO-TM6_2uILgI8NI0IjOm7FcwLABBKEMEo0/edit?tab=t.0#heading=h.zd57bzqasuuz

**Comment by ahg-g** [comment]
I think sig networking would be the most appropriate

**Comment by BenTheElder** [comment]
We just need agreement from a SIG to be responsible for hosting the project long term and to setup pointers in sigs.yaml and the README, it sounds like it could be SIG net and that sounds like the closest fit to me personally.

**Comment by ahg-g** [comment]
@robscott fyi

**Comment by BenTheElder** [comment]
FYI https://github.com/kubernetes/community/pull/8056, it was introduced under SIG Apps, actually.

I have a thread with the github management team about preventing this sort of confusion in the future by tweaking the request template to clearly ask for the sponsoring SIG for future repos to be one particular SIG.
In my case I saw the WG serving README PR and this repo's README but not the commit to SIG Apps, and both sigs listed in the request.

If you all are fine with SIG Apps being the sponsoring SIG, then lets just clarify the README here and in the wg-serving README/charter to make it clear that SIG Apps owns it and wg-serving is where it's being discussed.

**Comment by BenTheElder** [comment]
> I have a thread with the github management team about preventing this sort of confusion in the future by tweaking the request template to clearly ask for the sponsoring SIG for future repos to be one particular SIG.

[this part is done: https://github.com/kubernetes/org/pull/5266]

> I am open to the suggestion to put this under SIG Network, especially given that it has close ties with Gateway API and deals with application level routing and load-balancing for LLM inference traffic. However given what @BenTheElder is saying, it sounds like we should discuss this at some length. Looking forward to further discussion on this.

ACK, from talking to a few folks, it seems like SIG-Apps is OK but SIG Net may be a better fit, when you all have a conclusion if we need to change things just send a PR to kubernetes/community and this repo and we can update things.

I just ask that even if we don't move it, please cleanup references in this repo and in kubernetes/community wg-serving that indicate that wg serving "owns" this as opposed to a place to discuss this project being sponsored by Apps or Network.

Sometimes workgroups last for many years but they eventually wind down and the distinction is important, we make sure things roll up to SIGs because of this and because SIGs have carefully reviewed charters to avoid conflict, while as we see here it is normal and expected for working groups and conceptual efforts to span many SIGs, as opposed to projects.

Thanks all! Let me know if there's anything I can do to help.

**Comment by BenTheElder** [comment]
Filed one of the interim cleanup PRs at https://github.com/kubernetes/community/pull/8179

**Comment by terrytangyuan** [comment]
Based on @BenTheElder's comment https://github.com/kubernetes/community/pull/8179#discussion_r1853071389, Serving Catalog is not a project yet as it needs sponsorship from SIGs. cc @ahg-g @jjk-g

**Comment by ahg-g** [comment]
> Looking at https://github.com/kubernetes/community/pull/7988 it seems, it landed under sig-arch, although looking at https://github.com/kubernetes/org/issues/5072 I only see folks from sig-scheduling acking that repo.

The wg-serving repo is a generic playground for the working group, it is not meant to be only for the serving catalog. 

> Based on @BenTheElder's comment https://github.com/kubernetes/community/pull/8179#discussion_r1853071389, Serving Catalog is not a project yet as it needs sponsorship from SIGs. cc @ahg-g @jjk-g

Thanks for flagging, it is fine if we remove it.

**Comment by BenTheElder** [comment]
regarding:
> I just ask that even if we don't move it, please cleanup references in this repo and in kubernetes/community wg-serving that indicate that wg serving "owns" this as opposed to a place to discuss this project being sponsored by Apps or Network.

Filed https://github.com/kubernetes-sigs/llm-instance-gateway/pull/52 to close that out:
> I think this is reasonable? It allows WG-Serving to claim credit for launching this project, drives interest in the WG, but still clearly identifies the sponsoring SIG and the official subproject listing. I think the split into two sentences is more readable.

**Comment by shaneutt** [comment]
With https://github.com/kubernetes/community/pull/8211, it seems like we're all set :+1: 

/close

Re-open if there's anything else here we need to figure out.

**Comment by shaneutt** [comment]
Oh, actually right after this I noticed the README needs updates about this, as well as the community documentation it links to, so maybe we can hold this one open to cover the work needed to update the relevant documentation regarding SIG Network's role with this.

/reopen

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/92 Updated the readme.

**Comment by shaneutt** [comment]
Roger that, somehow I was looking at something out of date, perhaps my own fork. :+1: 

/close

**Comment by BenTheElder** [comment]
Thanks all.
